export * from "./create.js";
export * from "./plugin.js";
export * from "./sveltekit.js";
export type {
  AuthApi,
  AuthClient,
  AuthConfig,
  AuthSession,
  AuthUser,
  ClientsConfig,
  IssuedClient,
  IssuedClientToken,
  IssuedSession,
  OidcProviderConfig,
  SessionMetadata,
} from "@shuri/auth";
export {
  AccountLinkRefusedError,
  AuthConfigError,
  AuthenticationFailedError,
  AuthSlugCollisionError,
  ClientsConfigError,
  EmailAlreadyRegisteredError,
  InvalidCredentialsError,
  InvalidScopeError,
  MissingEmailClaimError,
  OAuthTransactionError,
  OidcProviderError,
  UnauthenticatedError,
  UnknownClientError,
  UnknownProviderError,
  UnknownRoleError,
  UnsupportedMediaTypeError,
  googleProvider,
  oidcProvider,
  usersCollection,
} from "@shuri/auth";
export { ForbiddenError } from "@shuri/api";
export type {
  AccessClient,
  AccessContext,
  AccessResult,
  AccessRule,
  AccessUser,
  CollectionAccess,
  CollectionAfterChangeArgs,
  CollectionAfterReadArgs,
  CollectionBeforeChangeArgs,
  CollectionBeforeReadArgs,
  CollectionDeleteArgs,
  CollectionHook,
  CollectionHookName,
  CollectionHooks,
  GlobalAccess,
  GlobalAfterChangeArgs,
  GlobalAfterReadArgs,
  GlobalBeforeChangeArgs,
  GlobalBeforeReadArgs,
  GlobalHook,
  GlobalHookName,
  GlobalHooks,
  OperationContext,
  Principal,
  WithId,
} from "@shuri/core";
export type { HookRegistry, Unsubscribe } from "@shuri/store";
