import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { idAt, mig } from "../migration/test-support.js";
import { bundleSource, bundleState, writeBundle } from "./bundle.js";

const a = mig(idAt(1, "init"), null);
const b = mig(idAt(2, "next"), a.id);

describe("bundleSource", () => {
  it("imports each migration as JSON numbered by chain position, and exports them in order", () => {
    expect(bundleSource([a, b])).toBe(
      [
        "// Generated by `shuri-migrate bundle`. Do not edit; do not commit.",
        `import m_0 from "./${a.id}.json" with { type: "json" };`,
        `import m_1 from "./${b.id}.json" with { type: "json" };`,
        "",
        "export default [m_0, m_1];",
        "",
      ].join("\n"),
    );
  });

  it("exports an empty array for an empty chain, with no imports", () => {
    const source = bundleSource([]);
    expect(source).not.toContain("import ");
    expect(source).toContain("export default [];");
  });

  it("prefixes a relative import directory so it stays a relative specifier", () => {
    expect(bundleSource([a], "../db")).toContain(`from "../db/${a.id}.json"`);
    expect(bundleSource([a], "db")).toContain(`from "./db/${a.id}.json"`);
  });
});

describe("bundle on disk", () => {
  let root: string;
  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), "shuri-migrate-bundle-"));
  });
  afterEach(() => rm(root, { recursive: true, force: true }));

  const target = () => ({
    out: join(root, "gen", "index.ts"),
    dir: join(root, "migrations"),
  });

  it("is missing, then current once written, stale when the chain moves on or the file is edited", async () => {
    expect(await bundleState(target(), [a])).toBe("missing");

    await writeBundle(target(), [a]);
    expect(await bundleState(target(), [a])).toBe("current");
    expect(await bundleState(target(), [a, b])).toBe("stale");

    await writeFile(target().out, "// tampered\n");
    expect(await bundleState(target(), [a])).toBe("stale");
  });

  it("imports relative to the bundle file, with posix separators", async () => {
    await writeBundle(target(), [a]);
    expect(await readFile(target().out, "utf8")).toContain(
      `from "../migrations/${a.id}.json"`,
    );
  });
});
