import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, sep } from "node:path";
import type { MigrationFile } from "../migration/types.js";

/**
 * The text of the generated bundle: every migration imported as JSON and exported as one array, in
 * chain order (`m_<n>`, `n` = position in the chain). Workers and bundlers import this instead of
 * reading the directory.
 * @param chain - The linear chain.
 * @param importDir - Directory of the JSON files, relative to the bundle file (posix, e.g. `.`).
 * @returns The module source.
 */
export function bundleSource(chain: readonly MigrationFile[], importDir = "."): string {
  const prefix =
    importDir === "."
      ? "./"
      : importDir.startsWith("./") || importDir.startsWith("../")
        ? `${importDir}/`
        : `./${importDir}/`;
  const imports = chain.map(
    (file, n) => `import m_${n} from "${prefix}${file.id}.json" with { type: "json" };`,
  );
  const list = chain.map((_, n) => `m_${n}`).join(", ");
  return [
    "// Generated by `shuri-migrate bundle`. Do not edit; do not commit.",
    ...imports,
    "",
    `export default [${list}];`,
    "",
  ].join("\n");
}

const toPosix = (path: string) => path.split(sep).join("/");

export type BundleState = "current" | "stale" | "missing";

/** Where a bundle goes and what it imports from. */
export interface BundleTarget {
  /** Absolute path of the bundle file. */
  out: string;
  /** Absolute path of the migrations directory. */
  dir: string;
}

const sourceFor = (target: BundleTarget, chain: readonly MigrationFile[]) =>
  bundleSource(chain, toPosix(relative(dirname(target.out), target.dir)) || ".");

/**
 * @param target - Bundle file and migrations directory.
 * @param chain - The linear chain.
 * @returns Whether the bundle on disk is what `writeBundle` would write.
 */
export async function bundleState(
  target: BundleTarget,
  chain: readonly MigrationFile[],
): Promise<BundleState> {
  let current: string;
  try {
    current = await readFile(target.out, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return "missing";
    throw error;
  }
  return current === sourceFor(target, chain) ? "current" : "stale";
}

/**
 * Writes the bundle (creating its directory).
 * @param target - Bundle file and migrations directory.
 * @param chain - The linear chain.
 */
export async function writeBundle(
  target: BundleTarget,
  chain: readonly MigrationFile[],
): Promise<void> {
  await mkdir(dirname(target.out), { recursive: true });
  await writeFile(target.out, sourceFor(target, chain), "utf8");
}
